### ISSUE TITLE
documentation needed for the "remove" command

### ISSUE THREAD

**Issue by lwlsn** [Nagasaki45/bibo#37]
if no [OPTIONS] or [SEARCH_TERMS] provided then deletes the whole bibliography. 

maybe needs a warning output before erasing everything?

**Comment by Nagasaki45** [comment]
Oh crap! Thanks for letting me know. Hope you didn't lose anything important. I see two possible solutions:
- Make sure that the remove command removes one entry at a time (like the open / edit command).
- Add some warning if more than X entries is affected.

I think I'll go for the 1st solution. Do you prefer the 2nd?
