### ISSUE TITLE
Autocompletion broke completion for paths (file, destination, database)

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/bibo#38]

**Comment by Nagasaki45** [comment]
There's no much to do here on bibo's side. The topic is discussed on click's issues (https://github.com/pallets/click/issues/780 & https://github.com/pallets/click/pull/782). Just wait for a patch upstream...

**Comment by Nagasaki45** [comment]
It's a bit of a bummer that click still doesn't support auto-completion for paths. I wonder if we should wait with alpha release until this is implemented.

**Comment by Kappers** [comment]
I agree that this is a pain, and that `bibo` isn't the place to patch this up - that being said, if this blocked alpha (which I think is reasonable), that'd be a shame.

I suppose it'd be easy enough to add an `autocomplete` function to the add `click.option` that just transformed current input into a glob and prompted matches. Maybe, a plugin could be added as dependency which handles this until click is sorted, e.g. somehow decorating the existing `add` command to provide a DIY auto-complete layer, creating a bespoke `addfile` (not ideal)....

**Comment by Nagasaki45** [comment]
I'm up for implementing a temporary solution. Don't think it should be a plugin. The goal is to give users a pleasant interface without plugins and use plugins for extras. Do you want to give it a shot? I can also do this, up to you :-)

**Comment by Kappers** [comment]
I'll give it a shot!  👍

**Comment by Nagasaki45** [comment]
Cool!!!

**Comment by Nagasaki45** [comment]
Fixed in 90aa658 and 851929b.
