### ISSUE TITLE
Add command should allow relative paths for files without enforcing destination heuristic

### ISSUE THREAD

**Issue by Kappers** [Nagasaki45/bibo#52]
Currently `» bibo add --file RELATIVE_PATH` will attempt to use the `--destination` heuristic if not explicitly passed as argument, prepending a potentially-incorrect path and raising a `FileNotFound` error.

Maybe, consider (1) attempting to resolve and evaluate relative path to check `os.path.isfile()` before falling back to the destination heuristic (2) letting users explicitly set valid destination path(s), instead of using heuristic, else explicitly enforcing absolute path use. Open to ideas!

**Comment by Nagasaki45** [comment]
I think the "correct" behaviour is to move the file to the folder determined by the destination heuristic, regardless of specifying it with relative or absolute path. For example, if my destination heuristic is `/home/myuser/bibo_library`, the command `bibo add --file path/to/paper.pdf` should put `paper.pdf` in `/home/myuser/bibo_library`. @Kappers, do you think it's a reasonable behaviour?

Will take a look at it later this week to correct it.

**Comment by Kappers** [comment]
> I think the "correct" behaviour is to move the file to the folder determined by the destination heuristic, regardless of specifying it with relative or absolute path. For example, if my destination heuristic is `/home/myuser/bibo_library`, the command `bibo add --file path/to/paper.pdf` should put `paper.pdf` in `/home/myuser/bibo_library`. @Kappers, do you think it's a reasonable behaviour?

I think that makes sense, as long as it's more apparent to the user where that destination heuristic is (better, where the `bibo_library` is) - hence my point about it being explicitly set, or at least, notified during `--add`. Maybe, it is safe to assume users will organise pdfs under one `bibo_library` directory for now.

This was a problem as I was unorganised/lazy after converting from Zotero. Once this issue is resolved, if it makes sense, I might put a plugin together to handle this conversion (i.e. moving files to `bibo_library` as necessary). I don't know if that should be vanilla `bibo` functionality yet.

**Comment by Nagasaki45** [comment]
Hi @Kappers! I was looking at this today but I don't think I get what's the problem. I tried adding a new entry, specifying a file with a relative path. It  was successfully added to the correct directly following the destination heuristic. Specifying destination (absolute or relative paths) also works. Do you want bibo to notify the user when the destination heuristic is used? It will be great if you could give an example of what you did, what was the actual behaviour, and what you expected.

**Comment by Kappers** [comment]
The problem I had before was that I had files split between old Zotero folders and a new flat-folder. I've changed that now - I'm not sure if its realistic that somebody would have files spread over different folders.

Maybe, some 'expected usage' is needed here. Usage is easy if (a) using a flat folder for all pdfs (b) during `bibo add --file` always specifying a file in some separate path, e.g. in downloads. The attempt to always copy can cause problems, I'm not fussed and working around it so happy to close the issue.

Below are two-examples you might be interested in.

(1) The file is already in the right place, with some name that conflicts with bibo-default.

```
(venv) TK-MAC :: PhD/bib » bibo add --doi "https://doi.org/..." --file files/Cannon_2019.pdf
Traceback (most recent call last):
  File "/Users/thomaskaplan/libs/venv/bin/bibo", line 11, in <module>
    load_entry_point('bibo==0.0.22', 'console_scripts', 'bibo')()

...

  File "/Users/thomaskaplan/libs/venv/lib/python3.8/shutil.py", line 409, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/thomaskaplan/libs/venv/lib/python3.8/shutil.py", line 239, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'files/Cannon_2019.pdf' and '.../files/cannon_2019.pdf' are the same file```
```

(2) The file is already placed in a sub-folder,  e.g. for pre-prints/early versions of something. There isn't a need to create a new copy of the file - `files/cannon_2019.pdf` created, where file specified was already in relative sub-folder `files/preprints/Cannon...pdf`.

```
(venv) TK-MAC :: PhD/bib » bibo list Cannon
(venv) TK-MAC :: PhD/bib » ls -1 files/*/*Cannon*
files/preprint/Cannon... .pdf
(venv) TK-MAC :: PhD/bib » bibo add --doi "https://doi.org/..." --file files/preprints/Cannon\ ... .pdf
(venv) TK-MAC :: PhD/bib » egrep "Cannon\_" main.bib -A10
@article{Cannon_2019,
  ...
  file = {.../files/cannon_2019.pdf}
}
```

**Comment by Nagasaki45** [comment]
Thanks @Kappers for the detailed answer! I get the issue(s) now. I think there are few subtleties here. First, the heuristic might not be obvious when the files are scattered in multiple directories. Maybe we should add a command that will give information about the default path, which is used when `--destination` is ommited. Do you think it will help make things clearer? We can create `bibo info` with room for future stats about the .bib file.

Re the 1st example. That's clearly a bug! We should either fail gracefully or override the file. What would you prefer? I tend to prefer the first option as it's safer.

Re the 2nd example. You can always edit the bib entry and modify its content manually when adding new entries. I use it all the time, for example, to create tags. I would recommend not to use the `--file` flag if the file is already in the expected path but manually define the file field in the bib entry instead. Does this make sense?

BTW, just a minor comment from reading your examples, you don't have to pass the full URL to the `--doi` flag. The DOI itself, like `10.1075/gest.16.2.01ken`, is enough.

**Comment by Kappers** [comment]
> Thanks @Kappers for the detailed answer! I get the issue(s) now. I think there are few subtleties here. First, the heuristic might not be obvious when the files are scattered in multiple directories. Maybe we should add a command that will give information about the default path, which is used when `--destination` is ommited. Do you think it will help make things clearer? We can create `bibo info` with room for future stats about the .bib file.

That sounds fine. I like logging that makes stuff clear, I wouldn't mind _always_ having explicit notes saying "I'm copying X to Y" when I run add with a file. 

> Re the 1st example. That's clearly a bug! We should either fail gracefully or override the file. What would you prefer? I tend to prefer the first option as it's safer.

If the file is already there and user is specifying it, I don't see much need to do anything but tell the user that the existing file is being used instead of any copying etc. Maybe, give them a prompt to confirm that's what they want.

> Re the 2nd example. You can always edit the bib entry and modify its content manually when adding new entries. I use it all the time, for example, to create tags. I would recommend not to use the `--file` flag if the file is already in the expected path but manually define the file field in the bib entry instead. Does this make sense?

Sure. Although it seems easy to do it as part of `bibo add`, especially as the user is specifying a valid path with the existing arg `--file`. Generally, I don't add many extra bib fields after running `bibo add`, `file` is usually the only one I immediately need. 

> BTW, just a minor comment from reading your examples, you don't have to pass the full URL to the `--doi` flag. The DOI itself, like `10.1075/gest.16.2.01ken`, is enough.

Awesome!

**Comment by Nagasaki45** [comment]
PR #55 adds a `--no-copy` option anywhere a file can be passed. It should cover the workflow of adding new entries to the database with a file already in the right place. Instead of moving the file around it adds its path to the entry and that's it.
Should solve most of the current issue, isn't it?

**Comment by Nagasaki45** [comment]
Also, 14765b4 prints to the user where files are copied to.

**Comment by Kappers** [comment]
That is perfect, I'll definitely be making use of this! Thanks!

**Comment by Nagasaki45** [comment]
Cool! The changes are now in master and version 0.0.23. Check it out!
:-)
