### ISSUE TITLE
Add documentation for developers

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/bibo#57]
- [x] How to install development environment
- [x] Running tests + linter
- [x] Submitting PRs to the `dev` branch
- [x] When submitting PRs, try to include the issue number in the commit message if relevant, as per [this tutorial](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords). Use `#XXX` to reference the issue or `Fix: #XXX` if issue fixed by the commit. 
- [x] Building the docs
- [x] Working on plugins

**Comment by Kappers** [comment]
Would code coverage be included in 'running tests'?

Might be worth considering the below:
- [ ] Style guidelines

Maybe even worth using some continuous integration service (travis or circle) and including some linting tool?

**Comment by Nagasaki45** [comment]
> Would code coverage be included in 'running tests'?

I don't think we should actively worry about that. Coverage runs automatically by travis.

> Might be worth considering the below:
> 
>     * [ ]  Style guidelines
> 
> 
> Maybe even worth using some continuous integration service (travis or circle) and including some linting tool?

Agree completely! Opened #63 for that.
