### ISSUE TITLE
Revert temp path completion when resolved upstream

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/bibo#64]
We hacked together a temporary path completion in #38 / #61. The issue should hopefully be solved by click itself (follow pallets/click#780 & pallets/click#782). Revert the temporary fix when there's a solution upstream.

**Comment by Nagasaki45** [comment]
Hi @Kappers! Click 8 was just released, with support for path completion. Tested it now and it looks like we don't need to do anything to get automatic path completion. Feel bad for deleting a bunch of your code from the repo, but I guess that's for good. Feel free to test / comment, and thanks for the contribution again.

**Comment by Kappers** [comment]
@Nagasaki45  Sorry for being slow, I was on holiday! I think it's great that click provides support for this, thanks for reverting this band-aid 😄
