### ISSUE TITLE
bibo list fails

### ISSUE THREAD

**Issue by rhaynes74** [Nagasaki45/bibo#79]
Hi folks, new bibo user here.  I exported my .bib file from zotero and ran bibo --database=file list and it scrolls through a ton of files and then fails with:

ZouDelayinducedtraveling2002 📁
 Zou, Xingfu (2002). Delay Induced Traveling Wave Fronts in Reacti on Diffusion Equations of {{KPP}}-{{Fisher}} Type
ZuluagaModelingoptimizationtheory2013 📁 🔗
Modeling and Optimization: Theory and Applications (2013)       
bibtex failed. Using a fallback citation method. Use --verbose for more information

I tried the --verbose flag but it doesn't seem to work.   Suggestions?

**Comment by Nagasaki45** [comment]
Hi @rhaynes74! Welcome to bibo and thanks for getting involved. It looks like `bibtex` failed to process the citations. Can you run the command with the `--verbose` flag again and check the top of the output? For example, try `bibo --database=file list --verbose | head -n 50`. The `bibtex` output to the standard error should appear at the top. Yes, it's a bit annoying that the error appears in one place and the debugging information at another. Let's solve your issue first and we can discuss improving the errors / warnings.

**Comment by rhaynes74** [comment]
Hi - many thanks for the response.  I managed to clean up the zotero output and in this case bibo list now works.     Workflow suggestions?

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by Nagasaki45** [comment]
Happy to hear it's working now. Can you please tell what bits of the `.bib` file caused the problem?

Regarding workflow, take a look at the [quick start guide](https://bibo.readthedocs.io/en/latest/guide.html). To be honest, there's no much beyond that.

I'm closing this issue now. Feel free to reopen if needed.

Cheers,
Tom
